[target.armv7-unknown-linux-gnueabihf]
image = "cross-openssl:latest"

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "OPENSSL_STATIC",
    "OPENSSL_LIB_DIR",
    "OPENSSL_INCLUDE_DIR",
    "CFLAGS",
]