[target.armv7-unknown-linux-gnueabihf]
image = "cross-openssl:latest"

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "OPENSSL_STATIC",
    "OPENSSL_LIB_DIR",
    "OPENSSL_INCLUDE_DIR",
    "CFLAGS",
]
# CFLAGS=-fPIC \
# OPENSSL_STATIC=1 OPENSSL_LIB_DIR=/opt/openssl/target/arm32_glibc215/lib \
# OPENSSL_INCLUDE_DIR=/opt/openssl/target/arm32_glibc215/include \
# cross build --target armv7-unknown-linux-gnueabihf 