[development]
address = "localhost"
port = 8000
workers = 1
log = "debug"
# secret_key = "sercret
# limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 80
workers = 1
log = "normal"

[production]
address = "0.0.0.0"
port = 8080
workers = 1
log = "critical"