[debug]
address = "127.0.0.1"
port = 8000
workers = 1
log_level = "debug"
# secret_key = "sercret
# limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8080
workers = 1
log_level = "normal"

[release]
address = "0.0.0.0"
port = 8080
workers = 1
log_level = "critical"